title: OPEN SOURCE
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://github.com/jangseokgyu
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: 개요
   url: /index.html
 - title: 역사
   url: /about
 - title: 메일
   url: /contact

social:
   github: jsk053
   twitter: jsk053
   facebook: jsk053
   email: jsk053@hanyang.ac.kr

google_analytics: "UA-58263416-1"
